FROM node:alpine

# RUN mkdir -p /root/.oci

# COPY ./src/configs/oci /root/.oci

WORKDIR /app

COPY package*.json /app
COPY tsconfig.build.json /app
RUN yarn install
RUN yarn build

COPY . /app

EXPOSE 3000

CMD ["yarn","start"]
