version: '3.4'

services:
  dev:
    working_dir: '/app'
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - '3000:3000'
    networks:
      - nestjs-network
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.local
  prod:
    working_dir: '/app'
    build:
      context: ./
      dockerfile: Dockerfile-prod
    ports:
      - '3000:3000'
    networks:
      - nestjs-network
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env.production

networks:
  nestjs-network:
